#!/usr/bin/env bash

set -e

main() {
  local step="${1:-1}"

  [ "${step}" -lt 2 ] && step1
  [ "${step}" -lt 3 ] && step2
  step3
}

step1() {
  echo "e2e: step1"
  npm ci
  npm ci --prefix server --production -s
  npm ci --prefix v0.0.1 --production -s
  npm ci --prefix v0.0.2 --production -s
  npm run build --prefix v0.0.2 -s
}

step2() {
  echo "e2e: step2"
  npm run build --prefix v0.0.1 -s
}

step3() {
  echo "e2e: step3"
  npm start -s --prefix server
}

main $@
